In [1]:
import gibbs
import numpy as np

In [2]:
N = 3  # neurons
K = 2  # states
T = 100000  # time steps
seed = None #1234 
num_rep = 10


pi=np.array([1,0])

gamma=np.array([[0.9,0.1],
                [0.1,0.9]])

r=np.array([[1,0],
            [0,1],
            [1,0],
            [0,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=2)"


gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0]
Gamma:
 [[0.9 0.1]
 [0.1 0.9]]
R:
 [[0.5 0. ]
 [0.  0.5]
 [0.5 0. ]
 [0.  0.5]]
100000 data points are generated, which are:
Generated firings: [2 2 2 ... 3 3 3]
Generated states: [0 0 0 ... 1 1 1]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.06333452 0.93666548]
Estimated Gamma =  [[0.84926161 0.15073839]
 [0.18087037 0.81912963]]
Estimated R =  [[0.11479527 0.41674246]
 [0.45234064 0.010997  ]
 [0.01291776 0.53239702]
 [0.41994633 0.03986353]]
Rep 1...
##########################
Estimated values for the parameters
Estimated Pi =  [0.38504813 0.61495187]
Estimated Gamma =  [[0.50322016 0.49677984]
 [0.2783632  0.7216368 ]]
Estimated R =  [[0.15375929 0.30726117]
 [0.63601526 0.03596454]
 [0.12788438 0.31671088]
 [0.08234107 0.3400634 ]]
Rep 2...
##########################
Estimated values for the parameters
Estimated Pi =  [0.36611262 0.63388738]
Estimated Gamm

In [3]:
N = 3  # neurons
K = 4  # states
T = 100000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0])
gamma=np.array([[0.85,0.05,0.05,0.05],
                [0.05,0.85,0.05,0.05],
                [0.05,0.05,0.85,0.05],
                [0.05,0.05,0.05,0.85]])
r=np.array([[1,0,1,0],
            [0,1,1,0],
            [1,0,0,1],
            [0,1,0,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=4)"


gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)


Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0]
Gamma:
 [[0.85 0.05 0.05 0.05]
 [0.05 0.85 0.05 0.05]
 [0.05 0.05 0.85 0.05]
 [0.05 0.05 0.05 0.85]]
R:
 [[0.5 0.  0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.5 0.  0.  0.5]
 [0.  0.5 0.  0.5]]
100000 data points are generated, which are:
Generated firings: [0 2 2 ... 2 3 0]
Generated states: [0 0 0 ... 3 3 0]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.26767148 0.12618628 0.47362171 0.13252053]
Estimated Gamma =  [[0.03186234 0.16171487 0.17980611 0.62661669]
 [0.1904287  0.21143828 0.22678342 0.37134961]
 [0.27969593 0.27496893 0.07997523 0.36535992]
 [0.09135666 0.31261235 0.18863418 0.40739682]]
Estimated R =  [[0.33226189 0.42669697 0.34137219 0.08163592]
 [0.0760109  0.30021031 0.06801876 0.35514426]
 [0.08125011 0.0041115  0.13541832 0.50821756]
 [0.51047711 0.26898122 0.45519072 0.05500227]]
Rep 1...
##########################
Estimated values for the parameter

In [4]:
N = 3  # neurons
K = 5  # states
T = 100000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0])
gamma=np.array([[0.8,0.05,0.05,0.05,0.05],
                [0.05,0.8,0.05,0.05,0.05],
                [0.05,0.05,0.8,0.05,0.05],
                [0.05,0.05,0.05,0.8,0.05],
                [0.05,0.05,0.05,0.05,0.8]])
r=np.array([[1,0,1,0,1],
            [0,1,1,0,0],
            [1,0,0,1,1],
            [0,1,0,1,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=5)"


gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)


Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0]
Gamma:
 [[0.8  0.05 0.05 0.05 0.05]
 [0.05 0.8  0.05 0.05 0.05]
 [0.05 0.05 0.8  0.05 0.05]
 [0.05 0.05 0.05 0.8  0.05]
 [0.05 0.05 0.05 0.05 0.8 ]]
R:
 [[0.5        0.         0.5        0.         0.33333333]
 [0.         0.5        0.5        0.         0.        ]
 [0.5        0.         0.         0.5        0.33333333]
 [0.         0.5        0.         0.5        0.33333333]]
100000 data points are generated, which are:
Generated firings: [0 2 0 ... 3 2 2]
Generated states: [0 0 0 ... 3 3 3]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.03748917 0.18913042 0.50458661 0.20941473 0.05937907]
Estimated Gamma =  [[0.15937272 0.42174485 0.13930215 0.14753483 0.13204544]
 [0.0936488  0.67676628 0.0931993  0.0770399  0.05934573]
 [0.04524922 0.08896056 0.38054571 0.03191079 0.45333372]
 [0.17311443 0.09033707 0.10156803 0.10657753 0.52840294]
 [0.02386084 0

In [5]:
N = 3  # neurons
K = 6  # states
T = 100000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0,0])
gamma=np.array([[0.75,0.05,0.05,0.05,0.05,0.05],
                [0.05,0.75,0.05,0.05,0.05,0.05],
                [0.05,0.05,0.75,0.05,0.05,0.05],
                [0.05,0.05,0.05,0.75,0.05,0.05],
                [0.05,0.05,0.05,0.05,0.75,0.05],
                [0.05,0.05,0.05,0.05,0.05,0.75]])
r=np.array([[1,0,1,0,1,1],
            [0,1,1,0,0,1],
            [1,0,0,1,1,0],
            [0,1,0,1,1,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=6)"

gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0 0]
Gamma:
 [[0.75 0.05 0.05 0.05 0.05 0.05]
 [0.05 0.75 0.05 0.05 0.05 0.05]
 [0.05 0.05 0.75 0.05 0.05 0.05]
 [0.05 0.05 0.05 0.75 0.05 0.05]
 [0.05 0.05 0.05 0.05 0.75 0.05]
 [0.05 0.05 0.05 0.05 0.05 0.75]]
R:
 [[0.5        0.         0.5        0.         0.33333333 0.33333333]
 [0.         0.5        0.5        0.         0.         0.33333333]
 [0.5        0.         0.         0.5        0.33333333 0.        ]
 [0.         0.5        0.         0.5        0.33333333 0.33333333]]
100000 data points are generated, which are:
Generated firings: [0 0 0 ... 2 0 1]
Generated states: [0 0 0 ... 4 4 1]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.00960629 0.06122362 0.02981787 0.44756781 0.08070498 0.37107943]
Estimated Gamma =  [[0.06939522 0.34397272 0.0708766  0.09275425 0.26133507 0.16166614]
 [0.18253991 0.17492849 0.13590344 0.02372409 0.15471693 0.328

In [6]:
N = 3  # neurons
K = 7  # states
T = 100000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0,0,0])
gamma=np.array([[0.7,0.05,0.05,0.05,0.05,0.05,0.05],
                [0.05,0.7,0.05,0.05,0.05,0.05,0.05],
                [0.05,0.05,0.7,0.05,0.05,0.05,0.05],
                [0.05,0.05,0.05,0.7,0.05,0.05,0.05],
                [0.05,0.05,0.05,0.05,0.7,0.05,0.05],
                [0.05,0.05,0.05,0.05,0.05,0.7,0.05],
                [0.05,0.05,0.05,0.05,0.05,0.05,0.7]])
r=np.array([[1,0,1,0,1,1,1],
            [0,1,1,0,0,1,1],
            [1,0,0,1,1,0,1],
            [0,1,0,1,1,1,0]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=7)"

gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0 0 0]
Gamma:
 [[0.7  0.05 0.05 0.05 0.05 0.05 0.05]
 [0.05 0.7  0.05 0.05 0.05 0.05 0.05]
 [0.05 0.05 0.7  0.05 0.05 0.05 0.05]
 [0.05 0.05 0.05 0.7  0.05 0.05 0.05]
 [0.05 0.05 0.05 0.05 0.7  0.05 0.05]
 [0.05 0.05 0.05 0.05 0.05 0.7  0.05]
 [0.05 0.05 0.05 0.05 0.05 0.05 0.7 ]]
R:
 [[0.5        0.         0.5        0.         0.33333333 0.33333333
  0.33333333]
 [0.         0.5        0.5        0.         0.         0.33333333
  0.33333333]
 [0.5        0.         0.         0.5        0.33333333 0.
  0.33333333]
 [0.         0.5        0.         0.5        0.33333333 0.33333333
  0.        ]]
100000 data points are generated, which are:
Generated firings: [0 2 0 ... 2 2 2]
Generated states: [0 0 0 ... 0 0 0]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.02095121 0.08262612 0.23074698 0.18790539 0.20121011 0.26843132
 0.00812887]
Estimated Gamma =  [[0.3

In [7]:
N = 3  # neurons
K = 8  # states
T = 100000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0,0,0,0])
gamma=np.array([[0.72,0.04,0.04,0.04,0.04,0.04,0.04,0.04],
                [0.04,0.72,0.04,0.04,0.04,0.04,0.04,0.04],
                [0.04,0.04,0.72,0.04,0.04,0.04,0.04,0.04],
                [0.04,0.04,0.04,0.72,0.04,0.04,0.04,0.04],
                [0.04,0.04,0.04,0.04,0.72,0.04,0.04,0.04],
                [0.04,0.04,0.04,0.04,0.04,0.72,0.04,0.04],
                [0.04,0.04,0.04,0.04,0.04,0.04,0.72,0.04],
                [0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.72]])
r=np.array([[1,0,1,0,1,1,1,0],
            [0,1,1,0,0,1,1,1],
            [1,0,0,1,1,0,1,1],
            [0,1,0,1,1,1,0,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=8)"

gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0 0 0 0]
Gamma:
 [[0.72 0.04 0.04 0.04 0.04 0.04 0.04 0.04]
 [0.04 0.72 0.04 0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.72 0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.72 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.72 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04 0.72 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04 0.04 0.72 0.04]
 [0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.72]]
R:
 [[0.5        0.         0.5        0.         0.33333333 0.33333333
  0.33333333 0.        ]
 [0.         0.5        0.5        0.         0.         0.33333333
  0.33333333 0.33333333]
 [0.5        0.         0.         0.5        0.33333333 0.
  0.33333333 0.33333333]
 [0.         0.5        0.         0.5        0.33333333 0.33333333
  0.         0.33333333]]
100000 data points are generated, which are:
Generated firings: [0 2 1 ... 0 1 2]
Generated states: [0 0 2 ... 2 2 4]
Rep 0...
##########################
Estimated values for the paramet