In [1]:
import gibbs
import numpy as np

In [2]:
N = 3  # neurons
K = 2  # states
T = 50000  # time steps
seed = None #1234 
num_rep = 10


pi=np.array([1,0])

gamma=np.array([[0.9,0.1],
                [0.1,0.9]])

r=np.array([[1,0],
            [0,1],
            [1,0],
            [0,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=2)"


gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0]
Gamma:
 [[0.9 0.1]
 [0.1 0.9]]
R:
 [[0.5 0. ]
 [0.  0.5]
 [0.5 0. ]
 [0.  0.5]]
50000 data points are generated, which are:
Generated firings: [0 0 2 ... 0 2 0]
Generated states: [0 0 0 ... 0 0 0]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.5850252 0.4149748]
Estimated Gamma =  [[0.73674314 0.26325686]
 [0.51378825 0.48621175]]
Estimated R =  [[0.97556893 0.89748502]
 [0.00648633 0.07011213]
 [0.01408459 0.02591715]
 [0.00386015 0.0064857 ]]
Rep 1...
##########################
Estimated values for the parameters
Estimated Pi =  [0.43424965 0.56575035]
Estimated Gamma =  [[0.1401471 0.8598529]
 [0.2370311 0.7629689]]
Estimated R =  [[0.8752045  0.9628356 ]
 [0.05429709 0.01602175]
 [0.03560423 0.00875051]
 [0.03489419 0.01239213]]
Rep 2...
##########################
Estimated values for the parameters
Estimated Pi =  [0.61398676 0.38601324]
Estimated Gamma =  [[

In [3]:
N = 3  # neurons
K = 4  # states
T = 50000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0])
gamma=np.array([[0.85,0.05,0.05,0.05],
                [0.05,0.85,0.05,0.05],
                [0.05,0.05,0.85,0.05],
                [0.05,0.05,0.05,0.85]])
r=np.array([[1,0,1,0],
            [0,1,1,0],
            [1,0,0,1],
            [0,1,0,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=4)"


gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0]
Gamma:
 [[0.85 0.05 0.05 0.05]
 [0.05 0.85 0.05 0.05]
 [0.05 0.05 0.85 0.05]
 [0.05 0.05 0.05 0.85]]
R:
 [[0.5 0.  0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.5 0.  0.  0.5]
 [0.  0.5 0.  0.5]]
50000 data points are generated, which are:
Generated firings: [0 2 2 ... 3 3 2]
Generated states: [0 0 0 ... 3 3 0]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.17476567 0.38658828 0.1398004  0.29884565]
Estimated Gamma =  [[0.03857825 0.30137987 0.3062328  0.35380909]
 [0.09809467 0.08996629 0.63201338 0.17992566]
 [0.03168219 0.25957223 0.5376554  0.17109018]
 [0.03994889 0.0928508  0.85716177 0.01003854]]
Estimated R =  [[0.63071913 0.29264254 0.0990109  0.47986904]
 [0.06469565 0.43521554 0.31925826 0.09734794]
 [0.2957497  0.24972974 0.57558433 0.39254205]
 [0.00883552 0.02241219 0.0061465  0.03024097]]
Rep 1...
##########################
Estimated values for the parameters

In [4]:
N = 3  # neurons
K = 5  # states
T = 50000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0])
gamma=np.array([[0.8,0.05,0.05,0.05,0.05],
                [0.05,0.8,0.05,0.05,0.05],
                [0.05,0.05,0.8,0.05,0.05],
                [0.05,0.05,0.05,0.8,0.05],
                [0.05,0.05,0.05,0.05,0.8]])
r=np.array([[1,0,1,0,1],
            [0,1,1,0,0],
            [1,0,0,1,1],
            [0,1,0,1,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=5)"


gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)


Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0]
Gamma:
 [[0.8  0.05 0.05 0.05 0.05]
 [0.05 0.8  0.05 0.05 0.05]
 [0.05 0.05 0.8  0.05 0.05]
 [0.05 0.05 0.05 0.8  0.05]
 [0.05 0.05 0.05 0.05 0.8 ]]
R:
 [[0.5        0.         0.5        0.         0.33333333]
 [0.         0.5        0.5        0.         0.        ]
 [0.5        0.         0.         0.5        0.33333333]
 [0.         0.5        0.         0.5        0.33333333]]
50000 data points are generated, which are:
Generated firings: [0 0 0 ... 2 3 3]
Generated states: [0 0 0 ... 3 3 3]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.25325494 0.2861533  0.13819913 0.16731266 0.15507997]
Estimated Gamma =  [[0.26989273 0.39626539 0.00877058 0.03472199 0.29034931]
 [0.5541309  0.32977863 0.0075563  0.07841659 0.03011758]
 [0.1534362  0.11346727 0.08810396 0.63314821 0.01184437]
 [0.16736403 0.15413675 0.34907025 0.2910312  0.03839777]
 [0.18403957 0.

In [5]:
N = 3  # neurons
K = 6  # states
T = 50000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0,0])
gamma=np.array([[0.75,0.05,0.05,0.05,0.05,0.05],
                [0.05,0.75,0.05,0.05,0.05,0.05],
                [0.05,0.05,0.75,0.05,0.05,0.05],
                [0.05,0.05,0.05,0.75,0.05,0.05],
                [0.05,0.05,0.05,0.05,0.75,0.05],
                [0.05,0.05,0.05,0.05,0.05,0.75]])
r=np.array([[1,0,1,0,1,1],
            [0,1,1,0,0,1],
            [1,0,0,1,1,0],
            [0,1,0,1,1,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=6)"

gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0 0]
Gamma:
 [[0.75 0.05 0.05 0.05 0.05 0.05]
 [0.05 0.75 0.05 0.05 0.05 0.05]
 [0.05 0.05 0.75 0.05 0.05 0.05]
 [0.05 0.05 0.05 0.75 0.05 0.05]
 [0.05 0.05 0.05 0.05 0.75 0.05]
 [0.05 0.05 0.05 0.05 0.05 0.75]]
R:
 [[0.5        0.         0.5        0.         0.33333333 0.33333333]
 [0.         0.5        0.5        0.         0.         0.33333333]
 [0.5        0.         0.         0.5        0.33333333 0.        ]
 [0.         0.5        0.         0.5        0.33333333 0.33333333]]
50000 data points are generated, which are:
Generated firings: [2 0 0 ... 1 0 2]
Generated states: [0 2 2 ... 5 4 4]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.39043266 0.07410213 0.05043296 0.26255173 0.12623053 0.09624998]
Estimated Gamma =  [[4.80827420e-03 4.10206371e-03 8.22848856e-02 4.54309725e-02
  1.08394960e-01 7.54978844e-01]
 [8.98091540e-03 1.13748097e-01 2.798

In [6]:
N = 3  # neurons
K = 7  # states
T = 50000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0,0,0])
gamma=np.array([[0.7,0.05,0.05,0.05,0.05,0.05,0.05],
                [0.05,0.7,0.05,0.05,0.05,0.05,0.05],
                [0.05,0.05,0.7,0.05,0.05,0.05,0.05],
                [0.05,0.05,0.05,0.7,0.05,0.05,0.05],
                [0.05,0.05,0.05,0.05,0.7,0.05,0.05],
                [0.05,0.05,0.05,0.05,0.05,0.7,0.05],
                [0.05,0.05,0.05,0.05,0.05,0.05,0.7]])
r=np.array([[1,0,1,0,1,1,1],
            [0,1,1,0,0,1,1],
            [1,0,0,1,1,0,1],
            [0,1,0,1,1,1,0]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=7)"

gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0 0 0]
Gamma:
 [[0.7  0.05 0.05 0.05 0.05 0.05 0.05]
 [0.05 0.7  0.05 0.05 0.05 0.05 0.05]
 [0.05 0.05 0.7  0.05 0.05 0.05 0.05]
 [0.05 0.05 0.05 0.7  0.05 0.05 0.05]
 [0.05 0.05 0.05 0.05 0.7  0.05 0.05]
 [0.05 0.05 0.05 0.05 0.05 0.7  0.05]
 [0.05 0.05 0.05 0.05 0.05 0.05 0.7 ]]
R:
 [[0.5        0.         0.5        0.         0.33333333 0.33333333
  0.33333333]
 [0.         0.5        0.5        0.         0.         0.33333333
  0.33333333]
 [0.5        0.         0.         0.5        0.33333333 0.
  0.33333333]
 [0.         0.5        0.         0.5        0.33333333 0.33333333
  0.        ]]
50000 data points are generated, which are:
Generated firings: [0 2 2 ... 0 0 0]
Generated states: [0 0 0 ... 2 4 4]
Rep 0...
##########################
Estimated values for the parameters
Estimated Pi =  [0.2092553  0.15457082 0.00840955 0.16016142 0.24366315 0.15820676
 0.065733  ]
Estimated Gamma =  [[0.06

In [7]:
N = 3  # neurons
K = 8  # states
T = 50000  # time steps
seed = None #1234 
num_rep = 10

#input: initialization of the parameters for the HMM
#pi, gamma, r = initialize_parameters(N, K, seed)

pi=np.array([1,0,0,0,0,0,0,0])
gamma=np.array([[0.72,0.04,0.04,0.04,0.04,0.04,0.04,0.04],
                [0.04,0.72,0.04,0.04,0.04,0.04,0.04,0.04],
                [0.04,0.04,0.72,0.04,0.04,0.04,0.04,0.04],
                [0.04,0.04,0.04,0.72,0.04,0.04,0.04,0.04],
                [0.04,0.04,0.04,0.04,0.72,0.04,0.04,0.04],
                [0.04,0.04,0.04,0.04,0.04,0.72,0.04,0.04],
                [0.04,0.04,0.04,0.04,0.04,0.04,0.72,0.04],
                [0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.72]])
r=np.array([[1,0,1,0,1,1,1,0],
            [0,1,1,0,0,1,1,1],
            [1,0,0,1,1,0,1,1],
            [0,1,0,1,1,1,0,1]])


type_run = "Complexity increased keeping gamma very unbalanced, and increasing K (K=8)"

gibbs.run_simulation(T, N, K, seed, num_rep, pi, gamma, r, type_run)

Data is generated according to an HMM with the following parameters:
Pi:
 [1 0 0 0 0 0 0 0]
Gamma:
 [[0.72 0.04 0.04 0.04 0.04 0.04 0.04 0.04]
 [0.04 0.72 0.04 0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.72 0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.72 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.72 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04 0.72 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04 0.04 0.72 0.04]
 [0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.72]]
R:
 [[0.5        0.         0.5        0.         0.33333333 0.33333333
  0.33333333 0.        ]
 [0.         0.5        0.5        0.         0.         0.33333333
  0.33333333 0.33333333]
 [0.5        0.         0.         0.5        0.33333333 0.
  0.33333333 0.33333333]
 [0.         0.5        0.         0.5        0.33333333 0.33333333
  0.         0.33333333]]
50000 data points are generated, which are:
Generated firings: [2 0 0 ... 0 0 2]
Generated states: [0 2 2 ... 0 0 0]
Rep 0...
##########################
Estimated values for the paramete