In [4]:
import numpy as np
import itertools

In [16]:
def initialize_parameters(N, K, seed=None):
    if seed is not None:
        np.random.seed(seed)

    # Probability vector of length K
    pi = np.random.dirichlet(alpha=np.ones(K))    

    assert(np.allclose(sum(pi), 1, atol=1e-6) == 1)

    # Transition matrix (K x K), where each column sums to 1, because a column
    # represents the jump probabilities from a fixed initial state.
    gamma = np.random.dirichlet(alpha=np.ones(K), size=K).T

    assert(np.allclose(np.sum(gamma, axis = 0), np.ones(K), atol=1e-6) == 1)

    # r matrix (N+1 x K), where each column sums to 1, because a column
    # represents the firing probability of a neuron in a fixed state.
    r = np.random.dirichlet(alpha=np.ones(N + 1), size=K).T

    assert(np.allclose(np.sum(r, axis = 0), np.ones(K), atol=1e-6))

    return pi, gamma, r

def generate_hmm_data(T, N, K, pi, gamma, r):
    z = np.zeros(T, dtype=int)
    y = np.zeros(T, dtype=int)

    # Initialization t=0. I extract the value of K following the init prob
    z[0] = np.random.choice(K, p=pi)
    y[0] = np.random.choice(N + 1, p=r[:, z[0]])

    #data generation
    for t in range(1, T):
        # I take the column of gamma corresponding to z[t-1] and extract from this distribution
        z[t] = np.random.choice(K, p=gamma[:, z[t-1]])
        
        # I take the column of r corresponding to z[t] and extract from this prob distribution
        y[t] = np.random.choice(N + 1, p=r[:, z[t]])

    return y, z

def likelihood_comp(T, K, pi, gamma, r, y):

    likelihood = 0
    # all possible sequences z
    all_sequences = itertools.product(range(K), repeat=T)

    for z in all_sequences: 

        p_1 = 0
        p_2 = pi[z[0]]

        for t in range(T-1):
            p_1 *= r[y[t], z[t]]
            p_2 *= gamma[z[t], z[t+1]]

        p_1 *= r[y[T-1], z[T-1]]

        likelihood += (p_1*p_2)

    return likelihood

In [17]:
N = 3  # neurons
K = 3  # states
T = 100  # time steps
seed = 1234  

#input: initialization of the parameters for the HMM
pi, gamma, r = initialize_parameters(N, K, seed)

print("pi = ", pi)
print("gamma = ", gamma)
print("r = ", r)

# print(r[y[0]])

#output: generation of the observed and hidden data
y, z = generate_hmm_data(T, N, K, pi, gamma, r)

print("y:", y)
print("z:", z)

# likelihood = likelihood_comp(T, K, pi, gamma, r, y)
# print(likelihood)

pi =  [0.12069069 0.55244944 0.32685987]
gamma =  [[0.45646788 0.06325535 0.64711981]
 [0.44912046 0.31643628 0.1373299 ]
 [0.09441166 0.62030837 0.21555029]]
r =  [[0.31227274 0.16121984 0.23302989]
 [0.33858345 0.00319615 0.49051518]
 [0.12553553 0.3416608  0.04023219]
 [0.22360828 0.49392322 0.23622274]]
y: [1 3 1 2 0 3 3 3 0 2 3 1 1 1 0 3 3 3 1 2 0 3 0 3 0 3 1 0 1 1 0 3 1 1 3 1 3
 2 3 1 0 1 3 0 3 1 0 3 3 3 0 3 0 3 1 0 0 1 3 1 1 0 1 1 0 3 3 3 3 3 3 1 3 1
 3 2 3 3 1 1 0 2 2 0 2 1 0 3 3 3 3 1 1 2 3 1 1 3 0 3]
z: [2 0 0 1 2 1 1 2 0 0 1 0 0 0 1 2 2 2 0 1 2 0 0 1 2 0 0 0 0 2 1 2 0 0 1 2 0
 0 1 2 2 0 0 0 1 2 0 1 2 1 1 1 1 1 2 0 2 0 0 2 0 1 2 2 0 1 2 1 1 2 2 0 1 2
 0 0 0 1 2 2 0 0 1 2 0 0 1 2 2 0 1 0 0 0 1 2 0 1 1 2]


In [429]:
a =[0.0619599,  0.84200031, 0.13520899]
b = [0.20247272, 0.31928411, 0.22289119]
print(sum(a))
print(sum(b))

1.0391692
0.74464802
